# %% [markdown]
# # [Title of your project]
# 
# - **Name:** [your name]
# - **Student ID:** [your student ID]

# %% [markdown]
# ## Requirements
# 
# Include a `requirements.txt` file listing all packages with **exact version numbers** to ensure reproducibility. For example:
# 
# ```requirements.txt
# jupyter==1.1.1
# pymovements==0.22.1
# ```
# 
# ### Additional files required to run this notebook
# 
# Ideally, you should include all files required to run the notebook in the submitted ZIP file (for example: the `requirements.txt` file, the `gctg.yaml` or `gctg-clean.yaml` file, any additional code or data files).
# 
# If you **cannot** include all the files for some reason (e.g., because they are too large), include instructions on how to get them. If possible, simply provide a link to the required files and specify in which directory it needs to be placed (relative to the notebook).

# %% [markdown]
# ## Introduction
# 
# The introduction should introduce the topic of your project. Make sure to explain why the topic is relevant (e.g., by naming possible applications, referring to previous research or theoretical background).
# 
# ### Research question/hypothesis
# 
# Clearly state your research question or hypothesis.
# 
# ### Methodology
# 
# You should also give a short high-level overview of what you did (which methods/datasets/models you used, what experiments you did). If you used our own dataset, you can simply refer to it as the "GCTG experiment/dataset". You do not have to explain the experiment design. If you used any other datasets, please provide a link to the paper.

# %% [markdown]
# ## Implementation and results
# 
# This section is where your code goes. We **will** read and run your code, so please make sure that it is well documented with comments and/or Markdown cells.
# 
# Refer to the [`preprocessing.ipynb`](../../preprocessing.ipynb) notebook for examples.
# 
# > **IMPORTANT:** Make sure to save and submit the notebook with generated outputs (i.e., plots and other outputs should be visible without re-running the code).

# %%
print("Your code here")

# %% [markdown]
# [More text in between]

# %%
print("More code here")

# %% [markdown]
# ## Discussion and conclusion
# 
# Summarize the most important findings in a concise manner. Explain how they relate to your question, theory, or previous research (refer back to your motivation!). Provide an answer to your research question (or reasons for why you can't answer it based on the results you got).

# %% [markdown]
# # AI usage declaration
# 
# I used the following tools:
# 
# | Tool           | Purpose                          |
# | -------------- | -------------------------------- |
# | ChatGPT        | Brainstorming research questions |
# | GitHub Copilot | Assistance with plotting code    |
# | Grammarly      | Grammar checking                 |
# | ...            | ...                              |
# 
# - I thoroughly checked all output generated by these tools.
# - I know that I am responsible for the correctness of all code and content in this report.
# - I confirm that (apart from the resources listed above) the code and content in this report is my own work.
# 
# **Signature:** [your name]
# 


